# Generated by Django 5.2 on 2025-04-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_de_usuarios_no_banco', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
